version: "3"

services:
  saleor-storefront:
    container_name: saleor-storefront
    build:
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SALEOR_API_URL: "http://172.18.0.4:8000/graphql/"
        NEXT_PUBLIC_STOREFRONT_URL: "http://localhost:3000"
    restart: always
    ports:
      - 3000:3000
    environment:
      NEXT_PUBLIC_SALEOR_API_URL: "http://172.18.0.4:8000/graphql/"
      NEXT_PUBLIC_STOREFRONT_URL: "http://localhost:3000"
    networks:
      - saleor-platform_default

networks:
  saleor-platform_default:
    external: true
